name: build-and-run-tests

on: [push]

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: get_packages
        run: sudo apt update && sudo apt install cmake

      - name: install_pytorch
        run: pip3 install torch --index-url https://download.pytorch.org/whl/cpu

      - name: install_numpy
        run: pip install numpy

      - name: get_repo
        uses: actions/checkout@v3
        with:
          path: main

      - name: configure_and_build
        shell: bash
        working-directory: ${{github.workspace}}/main/build_cpu
        run: |
          cmake -DCMAKE_PREFIX_PATH=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'` .
          cmake --build . --config Release

      - name: runtest
        shell: bash
        working-directory: ${{github.workspace}}/main/build_cpu
        run: ./test-net
